import { SVGGraphicsElement } from './index'

export class SVGSVGElement extends SVGGraphicsElement implements globalThis.SVGSVGElement {
  animationsPaused
  checkEnclosure
  checkIntersection
  contentScriptType
  contentStyleType
  createEvent
  createSVGAngle
  createSVGLength
  createSVGMatrix
  createSVGNumber
  createSVGPoint
  createSVGRect
  createSVGTransform
  createSVGTransformFromMatrix
  currentScale
  currentTranslate
  deselectAll
  forceRedraw
  getComputedStyle
  getCurrentTime
  getEnclosureList
  getIntersectionList
  height
  pauseAnimations
  pixelUnitToMillimeterX
  pixelUnitToMillimeterY
  preserveAspectRatio
  screenPixelToMillimeterX
  screenPixelToMillimeterY
  setCurrentTime
  suspendRedraw
  unpauseAnimations
  unsuspendRedraw
  unsuspendRedrawAll
  viewBox
  viewport
  width
  x
  y
  zoomAndPan

  nonce
  SVG_ZOOMANDPAN_DISABLE
  SVG_ZOOMANDPAN_MAGNIFY
  SVG_ZOOMANDPAN_UNKNOWN
}
