[package]
edition = "2018"
name = "graffiti"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
license = "MIT"

[lib]
name = "graffiti"
crate-type = ["rlib", "cdylib"]

[dependencies]
pom = "3.2.0"
fontdue = "0.4.0"
graffiti-glfw = { path = "graffiti-glfw" }
graffiti-yoga = { path = "graffiti-yoga" }
paste = "1.0"
fnv = "1.0.7"
dashmap = "4.0.2"

# --features=tiny_skia
tiny-skia = { git = "https://github.com/RazrFalcon/tiny-skia", rev = "7b5914d", optional = true }

[features]
default = []

# bindings
nodejs = []
deno = []

[profile.release]
# fix --release for raspi https://github.com/rust-lang/rust/issues/62896
codegen-units = 1

[[example]]
name = "tiny_skia"
path = "examples/tiny_skia.rs"
required-features = ["tiny-skia"]
