[package]
edition = "2018"
name = "graffiti"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
license = "MIT"

[lib]
name = "graffiti"
crate-type = ["rlib", "cdylib"]

[dependencies]
once_cell = "1.7.2"
pom = "3.2.0"
ab_glyph_rasterizer = "0.1.4"
fontdb = "0.5.1"
owned_ttf_parser = "0.9"
graffiti-glfw = { path = "graffiti-glfw" }
graffiti-yoga = { path = "graffiti-yoga" }
crossbeam-channel = "0.5.0"
dashmap = "4.0.2"
nanoserde = { git = "https://github.com/not-fl3/nanoserde", rev = "c66efbd" }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[profile.release]
# fix --release for raspi https://github.com/rust-lang/rust/issues/62896
codegen-units = 1
