[package]
edition = "2018"
name = "graffiti"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
license = "MIT"

[lib]
name = "graffiti"
crate-type = ["rlib", "cdylib"]

[dependencies]
once_cell = "1.7.2"
pom = "3.2.0"
#fontdue = "0.4.0"
fontdb = "0.5.1"
owned_ttf_parser = "0.9"
#rustybuzz = "0.3.0"
graffiti-glfw = { path = "graffiti-glfw" }
graffiti-yoga = { path = "graffiti-yoga" }
paste = "1.0"
fnv = "1.0.7"
dashmap = "4.0.2"
nanoserde = { git = "https://github.com/not-fl3/nanoserde", rev = "c66efbd" }
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

# --features=tiny_skia
tiny-skia = { git = "https://github.com/RazrFalcon/tiny-skia", rev = "7b5914d", optional = true }

[features]
default = []

[profile.release]
# fix --release for raspi https://github.com/rust-lang/rust/issues/62896
codegen-units = 1

[[example]]
name = "tiny_skia"
path = "examples/tiny_skia.rs"
required-features = ["tiny-skia"]
