[package]
edition = "2018"
name = "graffiti"
version = "0.1.0"
authors = ["Kamil Tomšík <info@tomsik.cz>"]
license = "MIT"

[lib]
name = "graffiti"
crate-type = ["rlib", "cdylib"]

[dependencies]
pom = "3.2.0"
graffiti-glfw = { path = "graffiti-glfw" }
# TODO: platform-specific font/text dylib(s)
graffiti-stb = { path = "graffiti-stb" }
stretch = { git = "https://github.com/cztomsik/stretch" }
gl = "0.14.0"
nanovg-sys = { version = "1.0.2", features = ["gl2"] }
# TODO: fork it & make serde optional
arc-interner = "0.5.0"
fnv = "1.0.7"

[features]
default = []

# nodejs bindings
nodejs = []

# deno bindings
deno = []

# include debug logs
debug = []
silly = []

[profile.release]
# fix raspi --release builds
# https://github.com/rust-lang/rust/issues/62896
codegen-units = 1
